src/Entity/AvForm.php
<?php

namespace App\Entity;

use App\Repository\AvFormRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AvFormRepository::class)]
class AvForm
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups([
        'api_av_form_index'
    ])]
    
    private ?string $message_form = null;

    #[ORM\ManyToOne]
    #[Groups([
        'api_av_form_index'
    ])]
    #[ORM\JoinColumn(nullable: false)]
    private ?AvTravel $AvTravel = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?AvStatus $AvStatus = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?AvUser $AvUser = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessageForm(): ?string
    {
        return $this->message_form;
    }

    public function setMessageForm(string $message_form): static
    {
        $this->message_form = $message_form;

        return $this;
    }

    public function getAvTravel(): ?AvTravel
    {
        return $this->AvTravel;
    }

    public function setAvTravel(?AvTravel $AvTravel): static
    {
        $this->AvTravel = $AvTravel;

        return $this;
    }

    public function getAvStatus(): ?AvStatus
    {
        return $this->AvStatus;
    }

    public function setAvStatus(?AvStatus $AvStatus): static
    {
        $this->AvStatus = $AvStatus;

        return $this;
    }

    public function getAvUser(): ?AvUser
    {
        return $this->AvUser;
    }

    public function setAvUser(?AvUser $AvUser): static
    {
        $this->AvUser = $AvUser;

        return $this;
    }
}

src/Form/AvFormType.php
<?php

namespace App\Form;

use App\Entity\AvForm;
use App\Entity\AvStatus;
use App\Entity\AvTravel;
use App\Entity\AvUser;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('message_form')
            ->add('AvTravel', EntityType::class, [
                'class' => AvTravel::class,
'choice_label' => 'id',
            ])
            ->add('AvStatus', EntityType::class, [
                'class' => AvStatus::class,
'choice_label' => 'id',
            ])
            ->add('AvUser', EntityType::class, [
                'class' => AvUser::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AvForm::class,
        ]);
    }
}

src/Controller/Api/AvFormController.php
<?php

namespace App\Controller\Api;

use App\Entity\AvForm;
use App\Entity\AvStatus;
use App\Entity\AvTravel;
use App\Entity\AvUser;
use App\Repository\AvFormRepository;
use App\Repository\AvTravelRepository;
use App\Repository\AvUserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Serializer\SerializerInterface as SerializerSerializerInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;


class AvFormController extends AbstractController
{


    #[Route('/api/av/form', name: 'api_av_form_', methods: ['POST'])]
    public function new(SerializerSerializerInterface $serializer, ValidatorInterface $validator, EntityManagerInterface $em, Request $request,  AvUserRepository $userRepository, AvFormRepository $formRepository): JsonResponse
    {
        $data = json_decode($request->getContent(), true);
        $firstname = $data["firstname_user"];
        $lastname = $data["lastname_user"];
        $password = $data["password"];
        $phone = $data["phone_user"];
        $email = $data["email"];
        $message = $data["message_form"] ?: "";
        $travel = $em->getRepository(AvTravel::class)->findOneBy(["id" => $data["id"]]);
        $status = $em->getRepository(AvStatus::class)->findOneBy(["id" => $data["status"]]);

        $existingAccount = $userRepository->findBy(['email' => $email]);
        if ($existingAccount) {
            return new JsonResponse(["message" => "L'email existe déjà"], Response::HTTP_CONFLICT);
        } else {

            $user = new AvUser();
            $user->setEmail($email);
            $user->setPhoneUser($phone);
            $user->setLastnameUser($lastname);
            $user->setFirstnameUser($firstname);
            $user->setPassword("ViveLesVacances");
            $user->setRoles(["ROLE_USER"]);


            $em->persist($user);
            $em->flush();
            $id = $em->getConnection()->lastInsertId();
            $user->setId($id);


            $newReservation = new AvForm();
            $newReservation->setMessageForm($message);
            $newReservation->setAvTravel($travel);
            $newReservation->setAvStatus($status);
            $newReservation->setAvUser($user);
            


            $em->persist($newReservation);
            $em->flush();


            $responseText = "Réservation envoyée";

            return new JsonResponse($responseText, Response::HTTP_OK);
        }
    }
}

src/Controller/AvFormController.php
<?php

namespace App\Controller;

use App\Entity\AvForm;
use App\Form\AvFormType;
use App\Repository\AvFormRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/av/form')]
#[IsGranted('ROLE_ADMIN', statusCode: 423, message: "Vous n'avez pas les droits pour accéder à cette page")]

class AvFormController extends AbstractController
{
    #[Route('/', name: 'app_av_form_index', methods: ['GET'])]
    public function index(AvFormRepository $avFormRepository): Response
    {
        return $this->render('av_form/index.html.twig', [
            'av_forms' => $avFormRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_av_form_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avForm = new AvForm();
        $form = $this->createForm(AvFormType::class, $avForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avForm);
            $entityManager->flush();

            return $this->redirectToRoute('app_av_form_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('av_form/new.html.twig', [
            'av_form' => $avForm,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_av_form_show', methods: ['GET'])]
    public function show(AvForm $avForm): Response
    {
        return $this->render('av_form/show.html.twig', [
            'av_form' => $avForm,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_av_form_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, AvForm $avForm, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvFormType::class, $avForm);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_av_form_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('av_form/edit.html.twig', [
            'av_form' => $avForm,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_av_form_delete', methods: ['POST'])]
    public function delete(Request $request, AvForm $avForm, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avForm->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($avForm);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_av_form_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/av_form/_delete_form.html.twig
<form method="post" action="{{ path('app_av_form_delete', {'id': av_form.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ av_form.id) }}">
        <button class="bg-red-400 rounded p-2 text-white m-2">Supprimer</button>

</form>

templates/av_form/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn bg-green-400 rounded p-2 m-2 text-white inline">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/av_form/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AvForm{% endblock %}

{% block body %}
    <h1>Editer AvForm</h1>

    {{ include('av_form/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_av_user_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>

    {{ include('av_form/_delete_form.html.twig') }}
{% endblock %}

templates/av_form/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AvForm index{% endblock %}

{% block body %}
    <h1 class="my-2 pb-6 text-yellow-400 text-2xl font-bold right-0">Demandes de réservation</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Message</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for av_form in av_forms %}
            <tr>
                <td>{{ av_form.id }}</td>
                <td>{{ av_form.messageForm }}</td>
                <td>
                    <a href="{{ path('app_av_travel_show', {'id': av_form.id}) }}"   class="flex bg-blue-400 rounded p-2 m-2 text-white inline">Détails</a>

                    <a href="{{ path('app_av_travel_edit', {'id': av_form.id}) }}"  class="flex bg-yellow-400 rounded p-2 m-2 text-white inline">Editer</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_av_form_new') }}"  class="bg-green-400 rounded p-2 m-2 text-white inline text-right my-4">Créer</a> #}
{% endblock %}

templates/av_form/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AvForm{% endblock %}

{% block body %}
    <h1>Create new AvForm</h1>

    {{ include('av_form/_form.html.twig') }}

    <a href="{{ path('app_av_user_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>
{% endblock %}

templates/av_form/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}AvForm{% endblock %}

{% block body %}
    <h1>Demandes de réservations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ av_form.id }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ av_form.messageForm }}</td>
            </tr>
            
        </tbody>
    </table>

    <a href="{{ path('app_av_form_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>

    <a href="{{ path('app_av_form_edit', {'id': av_form.id}) }}"  class="bg-yellow-400 rounded p-2 m-2 text-white inline">Editer</a>

    {{ include('av_form/_delete_form.html.twig') }}
{% endblock %}