src/Entity/AvUser.php
<?php

namespace App\Entity;

use App\Repository\AvUserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: AvUserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class AvUser implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 180)]
    #[Assert\NotBlank(message: "L'email' ne peut pas être vide.")]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[Assert\Length(min: 2, minMessage: "Le nom doit contenir au minimum 2 caractères.", max: 255, maxMessage: "Le nom doit faire au plus 255 caractères")]
    #[ORM\Column(length: 255)]
    private ?string $lastname_user = null;

    #[Assert\Length(min: 2, minMessage: "Le prénom doit contenir au minimum 2 caractères.", max: 255, maxMessage: "Le prénom doit faire au plus 255 caractères")]
    #[ORM\Column(length: 255)]
    private ?string $firstname_user = null;

    #[ORM\Column]
    private ?int $phone_user = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id)
    {
        $this->id = $id;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastnameUser(): ?string
    {
        return $this->lastname_user;
    }

    public function setLastnameUser(string $lastname_user): static
    {
        $this->lastname_user = $lastname_user;

        return $this;
    }

    public function getFirstnameUser(): ?string
    {
        return $this->firstname_user;
    }

    public function setFirstnameUser(string $firstname_user): static
    {
        $this->firstname_user = $firstname_user;

        return $this;
    }

    public function getPhoneUser(): ?int
    {
        return $this->phone_user;
    }

    public function setPhoneUser(int $phone_user): static
    {
        $this->phone_user = $phone_user;

        return $this;
    }
}

src/Form/AvUserType.php
<?php

namespace App\Form;

use App\Entity\AvUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvUserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'ROLE_USER' => 'ROLE_USER',
                    'ROLE_ADMIN' => 'ROLE_ADMIN',
                    'ROLE_EDITEUR' => 'ROLE_EDITEUR',
                    'ROLE_SUPER_ADMIN' => 'ROLE_SUPER_ADMIN',
                ],
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('password')
            ->add('lastname_user')
            ->add('firstname_user')
            ->add('phone_user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AvUser::class,
        ]);
    }
}

src/Controller/AvUserController.php
<?php

namespace App\Controller;

use App\Entity\AvUser;
use App\Form\AvUserType;
use App\Repository\AvUserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


#[Route('/av/user')]
#[IsGranted('ROLE_ADMIN', statusCode: 423, message: "Vous n'avez pas les droits pour accéder à cette page")]
class AvUserController extends AbstractController
{
    #[Route('/', name: 'app_av_user_index', methods: ['GET'])]
    public function index(AvUserRepository $avUserRepository): Response
    {
        return $this->render('av_user/index.html.twig', [
            'av_users' => $avUserRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_av_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avUser = new AvUser();
        $form = $this->createForm(AvUserType::class, $avUser);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avUser);
            $entityManager->flush();

            $this->addFlash('success', "L'utilisateur' a bien été enregistré.");
            return $this->redirectToRoute('app_av_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('av_user/new.html.twig', [
            'av_user' => $avUser,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_av_user_show', methods: ['GET'])]
    public function show(AvUser $avUser): Response
    {
        return $this->render('av_user/show.html.twig', [
            'av_user' => $avUser,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_av_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, AvUser $avUser, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvUserType::class, $avUser);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash('success', 'Modification effectuée');
            return $this->redirectToRoute('app_av_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('av_user/edit.html.twig', [
            'av_user' => $avUser,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_av_user_delete', methods: ['POST'])]
    public function delete(Request $request, AvUser $avUser, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avUser->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($avUser);
            $entityManager->flush();
            $this->addFlash('success', 'Utilisateur supprimé');
        }

        return $this->redirectToRoute('app_av_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/av_user/_delete_form.html.twig
<form method="post" action="{{ path('app_av_user_delete', {'id': av_user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ av_user.id) }}">
    <button class="bg-red-400 rounded p-2 text-white m-2">Supprimer</button>
</form>

templates/av_user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    
    <button class="btn bg-green-400 rounded p-2 m-2 text-white inline">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/av_user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer un utilisateur{% endblock %}

{% block body %}
    <h1>Editer un utilisateur</h1>

    {% for message in app.flashes('success') %}
		<div class="bg-success">
			{{ message | join('<br>') }}
		</div>
	{% endfor %}

    {{ include('av_user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_av_user_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>

    {{ include('av_user/_delete_form.html.twig') }}
{% endblock %}

templates/av_user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des utilisateurs{% endblock %}

 

{% block body %}

{{ include('includes/success.html.twig') }}
{% for message in app.flashes('success') %}
		<div>
			{{ message | join('<br>') }}
		</div>
	{% endfor %}


    <h1 class="my-2 text-yellow-400 text-2xl font-bold pb-6">Liste des utilisateurs</h1>

    <div class="flex justify-end">
        <a href="{{ path('app_av_user_new') }}"  class="bg-green-400 rounded p-2 m-3 text-white inline my-4">Créer un nouvel utilisateur</a>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th class="p-2">Id</th>
                <th class="p-2">Nom</th>
                <th class="p-2">Prénom</th>
                <th class="p-2">Email</th>
                <th class="p-2">Téléphone</th>
                <th class="p-2">Role</th>
                <th class="p-2">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for av_user in av_users %}
            <tr>
                <td class="p-2 border-l-2">{{ av_user.id }}</td>
                <td class="p-2 border-l-2">{{ av_user.lastnameUser }}</td>
                <td class="p-2 border-l-2">{{ av_user.firstnameUser }}</td> 
                <td class="p-2 border-l-2">{{ av_user.email }}</td>
                <td class="p-2 border-l-2">{{ av_user.phoneUser }}</td> 
                <td class="p-2 border-l-2 w-40">{{ av_user.roles ? av_user.roles|json_encode : '' }}</td>
                
               
               
                <td class="p-2">
                    <a href="{{ path('app_av_user_show', {'id': av_user.id}) }} "   class="flex bg-blue-400 rounded p-1 ml-1 my-1 text-white inline">Détails</a>
                    <a href="{{ path('app_av_user_edit', {'id': av_user.id}) }}"  class="flex bg-yellow-400 rounded p-1 ml-1 my-1 text-white inline">Editer</a>
                    
                </td>
            </tr>
        {% else %}
            <tr class="flex w-full">
                <td colspan="8">Aucun utilisateur trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/av_user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AvUser{% endblock %}

{% block body %}

    <h1>Créer un nouvel utilisateur</h1>
	
{% for message in app.flashes('success') %}
		<div class="bg-success">
			{{ message | join('<br>') }}
		</div>
	{% endfor %}
	
	{{ include('includes/success.html.twig') }}

    {{ include('av_user/_form.html.twig') }}

	

    <a href="{{ path('app_av_user_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>

{% endblock %}

templates/av_user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}
    <h1>Liste des utilisateurs</h1>

    <table class="">
        <tbody class="">
            <tr class="">
                <th class="">Id</th>
                <td class="">{{ av_user.id }}</td>
            </tr>
            <tr class="">
                <th class="">Email</th>
                <td class="">{{ av_user.email }}</td>
            </tr>
            <tr class="">
                <th class="">Roles</th>
                <td class="">{{ av_user.roles ? av_user.roles|json_encode : '' }}</td>
            </tr>
            <tr class="">
                <th class="">Lastname_user</th>
                <td class="">{{ av_user.lastnameUser }}</td>
            </tr>
            <tr class="">
                <th class="">Firstname_user</th>
                <td class="">{{ av_user.firstnameUser }}</td>
            </tr>
            <tr class="" >
                <th class="">Phone_user</th>
                <td class="">{{ av_user.phoneUser }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_av_user_index') }}"  class="bg-blue-400 rounded p-2 m-2 inline text-white">Retour à la liste</a>

    <a href="{{ path('app_av_user_edit', {'id': av_user.id}) }}"  class="bg-yellow-400 rounded p-2 m-2 text-white inline">Editer</a>

    {{ include('av_user/_delete_form.html.twig') }}
{% endblock %}