src/Entity/AvTravel.php
<?php

namespace App\Entity;

use App\Repository\AvTravelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: AvTravelRepository::class)]
class AvTravel
{
    #[ORM\Id]
    #[Groups([
        'api_av_travel_index'
    ])]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?string $title_travel = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?string $picture_travel = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?string $description_travel = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?\DateTimeInterface $datestart_travel = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?\DateTimeInterface $dateend_travel = null;

    #[ORM\Column]
    #[Groups([
        'api_av_travel_index'
    ])]
    private ?int $price_travel = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?AvUser $AvUser = null;

    /**
     * @var Collection<int, AvCategory>
     */
    #[ORM\ManyToMany(targetEntity: AvCategory::class)]
    #[Groups([
        'api_av_travel_index'
    ])]
    private Collection $AvCategory;

    /**
     * @var Collection<int, AvCountry>
     */
    #[ORM\ManyToMany(targetEntity: AvCountry::class)]
    
    private Collection $AvCountry;

    public function __construct()
    {
        $this->AvCategory = new ArrayCollection();
        $this->AvCountry = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitleTravel(): ?string
    {
        return $this->title_travel;
    }

    public function setTitleTravel(string $title_travel): static
    {
        $this->title_travel = $title_travel;

        return $this;
    }

    public function getPictureTravel(): ?string
    {
        return $this->picture_travel;
    }

    public function setPictureTravel(?string $picture_travel): static
    {
        $this->picture_travel = $picture_travel;

        return $this;
    }

    public function getDescriptionTravel(): ?string
    {
        return $this->description_travel;
    }

    public function setDescriptionTravel(string $description_travel): static
    {
        $this->description_travel = $description_travel;

        return $this;
    }

    public function getDatestartTravel(): ?\DateTimeInterface
    {
        return $this->datestart_travel;
    }

    public function setDatestartTravel(\DateTimeInterface $datestart_travel): static
    {
        $this->datestart_travel = $datestart_travel;

        return $this;
    }

    public function getDateendTravel(): ?\DateTimeInterface
    {
        return $this->dateend_travel;
    }

    public function setDateendTravel(\DateTimeInterface $dateend_travel): static
    {
        $this->dateend_travel = $dateend_travel;

        return $this;
    }

    public function getPriceTravel(): ?int
    {
        return $this->price_travel;
    }

    public function setPriceTravel(int $price_travel): static
    {
        $this->price_travel = $price_travel;

        return $this;
    }

    public function getAvUser(): ?AvUser
    {
        return $this->AvUser;
    }

    public function setAvUser(?AvUser $AvUser): static
    {
        $this->AvUser = $AvUser;

        return $this;
    }

    /**
     * @return Collection<int, AvCategory>
     */
    public function getAvCategory(): Collection
    {
        return $this->AvCategory;
    }

    public function addAvCategory(AvCategory $avCategory): static
    {
        if (!$this->AvCategory->contains($avCategory)) {
            $this->AvCategory->add($avCategory);
        }

        return $this;
    }

    public function removeAvCategory(AvCategory $avCategory): static
    {
        $this->AvCategory->removeElement($avCategory);

        return $this;
    }

    /**
     * @return Collection<int, AvCountry>
     */
    public function getAvCountry(): Collection
    {
        return $this->AvCountry;
    }

    public function addAvCountry(AvCountry $avCountry): static
    {
        if (!$this->AvCountry->contains($avCountry)) {
            $this->AvCountry->add($avCountry);
        }

        return $this;
    }

    public function removeAvCountry(AvCountry $avCountry): static
    {
        $this->AvCountry->removeElement($avCountry);

        return $this;
    }
}

src/Form/AvTravelType.php
<?php

namespace App\Form;

use App\Entity\AvCategory;
use App\Entity\AvCountry;
use App\Entity\AvTravel;
use App\Entity\AvUser;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvTravelType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title_travel')
            ->add('picture_travel')
            ->add('description_travel')
            ->add('datestart_travel', null, [
                'widget' => 'single_text'
            ])
            ->add('dateend_travel', null, [
                'widget' => 'single_text'
            ])
            ->add('price_travel')
            ->add('AvUser', EntityType::class, [
                'class' => AvUser::class,
'choice_label' => 'id',
            ])
            ->add('AvCategory', EntityType::class, [
                'class' => AvCategory::class,
'choice_label' => 'id',
'multiple' => true,
            ])
            ->add('AvCountry', EntityType::class, [
                'class' => AvCountry::class,
'choice_label' => 'id',
'multiple' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => AvTravel::class,
        ]);
    }
}

src/Controller/Api/AvTravelController.php
<?php

namespace App\Controller\Api;

use App\Entity\AvTravel;
use App\Repository\AvCategoryRepository;
use App\Repository\AvTravelRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/api/av/travel', name: 'api_av_travel_')]  
class AvTravelController extends AbstractController
{
    #[Route('/index', name: 'index')]
    public function index(AvTravelRepository $tr, AvCategoryRepository $cr): JsonResponse
    {
        $travels = $tr->findAll();
        $categories = $cr->findAll();
        return $this->json(["travel" => $travels, "categories" => $categories], context:['groups' => "api_av_travel_index"], );

    }

    #[Route('/{id}', name: 'id')]
    public function travelDetails(AvTravelRepository $tr, int $id): JsonResponse
    {
        $travels = $tr->find($id);
        return $this->json($travels, context: ['groups' => "api_av_travel_index"]);
    }

    #[Route('/newness', name: 'newness')]
    public function travelNewness(AvTravelRepository $tr, int $id): JsonResponse
    {
        $travels = $tr->findAll();
        return $this->json($travels, context: ['groups' => "api_av_travel_index"]);
    }

    #[Route('/category/show', name: 'category')]
    public function categoriesFilter(AvTravelRepository $tr): JsonResponse
    {
        $categories = $tr->findAll();
        return $this->json($categories, context: ['groups' => "api_av_travel_index"]);
    }

    #[Route('/categoriesFilter/{id}', name: 'api_av_categories_', methods: ["GET"])]
    public function filterByCategory(EntityManagerInterface $em, int $id): JsonResponse
    {
        $qb = $em->createQueryBuilder();

        $categories = $qb->select('travel')
        ->from(AvTravel::class, 'travel')
        ->join('travel.AvCategory', 'category_travel')
        ->where('category_travel.id = :id')
        ->setParameter('id', $id)
        ->getQuery()
            ->getResult();

        return $this->json($categories, context: [
            'groups' =>  ["api_av_travel_index"]
        ]);
    }
    
}

src/Controller/AvTravelController.php
<?php

namespace App\Controller;

use App\Entity\AvTravel;
use App\Form\AvTravelType;
use App\Repository\AvTravelRepository;
use App\Repository\AvUserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/av/travel')]
class AvTravelController extends AbstractController
{
    #[Route('/', name: 'app_av_travel_index', methods: ['GET'])]
    public function index(AvTravelRepository $avTravelRepository): Response
    {
        $user = $this->getUser();
        return $this->render('av_travel/index.html.twig', [
            'av_travels' => $avTravelRepository->findAll(),
            'av_user' => $user
        ]);
        
    }

    #[Route('/new', name: 'app_av_travel_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avTravel = new AvTravel();
        $form = $this->createForm(AvTravelType::class, $avTravel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avTravel);
            $entityManager->flush();

            
            return $this->redirectToRoute('app_av_travel_index', [], Response::HTTP_SEE_OTHER);
        }
        
        $this->addFlash('success', 'Le voyage est créé.');
        return $this->render('av_travel/new.html.twig', [
            'av_travel' => $avTravel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_av_travel_show', methods: ['GET'])]
    public function show(AvTravel $avTravel): Response
    {
        return $this->render('av_travel/show.html.twig', [
            'av_travel' => $avTravel,
        ]);
    }

    #[IsGranted('ROLE_EDITEUR', statusCode: 423, message: "Vous ne pouvez modifier que vos annonces")]
    #[Route('/{id}/edit', name: 'app_av_travel_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, AvTravel $avTravel, EntityManagerInterface $entityManager): Response
    {
        
        $form = $this->createForm(AvTravelType::class, $avTravel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash('success', 'Le voyage a été modifié.');
            return $this->redirectToRoute('app_av_travel_index', [], Response::HTTP_SEE_OTHER);
        }
        
        return $this->render('av_travel/edit.html.twig', [
            'av_travel' => $avTravel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_av_travel_delete', methods: ['POST'])]
    public function delete(Request $request, AvTravel $avTravel, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avTravel->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($avTravel);
            $entityManager->flush();
        }
        
        $this->addFlash('success', 'Le voyage a été supprimé.');
        return $this->redirectToRoute('app_av_travel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/av_travel/_delete_form.html.twig
<form method="post" action="{{ path('app_av_travel_delete', {'id': av_travel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ av_travel.id) }}">
    <button class="bg-red-400 rounded p-2 text-white m-2">Supprimer</button>
</form>

templates/av_travel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn bg-green-400 rounded p-2 m-2 text-white inline">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/av_travel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit AvTravel{% endblock %}

{% block body %}
    <h1>Editer un voyage</h1>

    {% for message in app.flashes('success') %}
		<div class="bg-yellow-400 text-black">
			{{ message | join('<br>') }}
		</div>
	{% endfor %}

    {{ include('av_travel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_av_travel_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>

    {{ include('av_travel/_delete_form.html.twig') }}
{% endblock %}

templates/av_travel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AvTravel index{% endblock %}

{% block body %}
    <h1 class="my-2 text-yellow-400 text-2xl font-bold mb-6 ">Liste des voyages</h1>

   

    <div class="flex justify-end">
        <a href="{{ path('app_av_travel_new') }}"  class="bg-green-400 rounded p-2 m-3 text-white inline my-4">Créer un nouveau voyage</a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th class="p-1">Id</th>
                <th class="p-1">Voyages</th>
                <th class="p-1">Image</th>
                <th class="p-1">Description</th>
                <th class="p-1">Date de départ</th>
                <th class="p-1">Date de retour</th>
                <th class="p-1">Prix</th>
                <th class="p-1">Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for av_travel in av_travels %}
            <tr>
                <td class="p-3">{{ av_travel.id }}</td>
                <td class="p-3">{{ av_travel.titleTravel }}</td>
                <td class="p-3"><img src="{{ av_travel.pictureTravel }}" alt=""></td>
                <td class="p-3">{{ av_travel.descriptionTravel }}</td>
                <td class="p-3">{{ av_travel.datestartTravel ? av_travel.datestartTravel|date('d-m-Y') : '' }}</td>
                <td class="p-3">{{ av_travel.dateendTravel ? av_travel.dateendTravel|date('d-m-Y') : '' }}</td>
                <td class="p-3">{{ av_travel.priceTravel }}€</td>
                <td class="p-1">
                
                    <a href="{{ path('app_av_travel_show', {'id': av_travel.id}) }}"   class="flex bg-blue-400 rounded p-1 my-1 text-white inline">Détails</a>
                    
                    {% if is_granted('ROLE_ADMIN') or av_user.id == av_travel.AvUser.id %}
                    <a href="{{ path('app_av_travel_edit', {'id': av_travel.id}) }}"  class="flex bg-yellow-400 rounded p-1 ml-1 text-white inline">Editer</a>

                    {% endif %}

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun utilisateur trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    
{% endblock %}

templates/av_travel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New AvTravel{% endblock %}

{% block body %}
    <h1>Create new AvTravel</h1>

    {% for message in app.flashes('success') %}
		<div class="bg-yellow-400 text-black">
			{{ message | join('<br>') }}
		</div>
	{% endfor %}

    {{ include('av_travel/_form.html.twig') }}

    <a href="{{ path('app_av_travel_index') }}"  class="bg-blue-400 rounded p-2 m-2 text-white inline">Retour à la liste</a>
{% endblock %}

templates/av_travel/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}AvTravel{% endblock %}

{% block body %}
    <h1 class="text-xl font-bold text-yellow-400 py-5">Voyage : {{ av_travel.titleTravel }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ av_travel.id }}</td>
            </tr>
            <tr>
                <th>Title_travel</th>
                <td>{{ av_travel.titleTravel }}</td>
            </tr>
            <tr>
                <th>Picture_travel</th>
                <td>{{ av_travel.pictureTravel }}</td>
            </tr>
            <tr>
                <th>Description_travel</th>
                <td>{{ av_travel.descriptionTravel }}</td>
            </tr>
            <tr>
                <th>Datestart_travel</th>
                <td>{{ av_travel.datestartTravel ? av_travel.datestartTravel|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Dateend_travel</th>
                <td>{{ av_travel.dateendTravel ? av_travel.dateendTravel|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Price_travel</th>
                <td>{{ av_travel.priceTravel }}</td>
            </tr>
        </tbody>
    </table>
    <div class="flex pt-5">
    <a href="{{ path('app_av_travel_index') }}"  class="bg-blue-400 rounded p-2 m-2 inline text-white">Retour à la liste</a>

    <a href="{{ path('app_av_travel_edit', {'id': av_travel.id}) }}"  class="bg-yellow-400 rounded p-2 m-2 text-white inline">Editer</a>

    </div>



    {{ include('av_travel/_delete_form.html.twig') }}
{% endblock %}